---
title: "Clean Power Alliance Service Territory"
description: |
  Part of the Local Clean Energy Vision for Southern California project.
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<a href = "https://cleanpoweralliance.org/">Clean Power Alliance</a> currently serves commercial and residential customers in thirty member jurisdictions and the unincorporated portions of Los Angeles and Ventura Counties, shown in teal below.  In these places, customers are autmatically enrolled to receive electricity from Clean Power Alliance.  Each jurisdiction has a default percentage of electricity coming from renewable energy sources, choosing 36% (light green on the map), 50% (medium green), or 100% (dark green). Cities that are not member jurisdictions of Clean Power Alliance are shown here with black outlines. 

<iframe src="webmap/webmap.html" width=1024 height=500></iframe>

Customers have the option of opting-up to a higher percentage of their electricity coming from renewable energy sources, opting-down, or opting out entirely and receiving their electricity exclusively from Southern California Edison.  Clean Power Alliance purchases renewable energy and delivers it via the grid maintained by Southern California Edison.

This webmap was created in December 2020 in support of the Local Clean Energy Vision for Southern California project.